import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { logoutAction, saveHero, saveSiteSettings } from "@/app/actions";

const fields=(row:Record<string,unknown>,names:string[])=>names.map(n=><div className="field" key={n}><label htmlFor={n}>{n.replaceAll("_"," ")}</label>{n.includes("blurb")||n.includes("subtitle")||n.includes("patronage")?<textarea id={n} name={n} defaultValue={String(row[n]??"")}/>:<input id={n} name={n} defaultValue={String(row[n]??"")} required/>}</div>);
export const dynamic="force-dynamic";
export default async function Admin({searchParams}:{searchParams:Promise<{status?:string}>}){
  const user=await requireAdmin(); const database=await db(); const [site,hero]=await Promise.all([database.prepare("SELECT * FROM site_settings WHERE id=1").first<Record<string,unknown>>(),database.prepare("SELECT * FROM hero WHERE id=1").first<Record<string,unknown>>()]); if(!site||!hero) throw new Error("Seed the CMS first."); const {status}=await searchParams;
  const collections=["site_settings","hero","stats","highlights","programmes","speakers","testimonials","sponsors","news","ctas","seo_defaults"];
  return <main className="admin-shell"><div className="admin-top"><div><p className="eyebrow">GITEX CMS</p><h1>Content dashboard</h1><small>Signed in as {user.email}</small></div><div><Link href="/en">View site ↗</Link> · <form action={logoutAction} style={{display:"inline"}}><button>Log out</button></form></div></div><div className="admin-grid"><aside className="panel"><h3>Collections</h3><ul className="collection-list">{collections.map(c=><li key={c}>{c}</li>)}</ul><p><small>Brief #1 enables editing for Site settings and Hero. Remaining collections are D1-backed and ready for the next admin UI increment.</small></p></aside><section>{status&&<p className="status">Changes saved. Public pages now use the updated content.</p>}<form className="panel" action={saveHero}><h2>Hero</h2><div className="form-grid">{fields(hero,["eyebrow_en","eyebrow_ru","title_en","title_ru","subtitle_en","subtitle_ru","countdown_target","patronage_line_en","patronage_line_ru"])}</div><button className="save">SAVE HERO</button></form><form className="panel" action={saveSiteSettings} style={{marginTop:24}}><h2>Site settings</h2><div className="form-grid">{fields(site,["site_name_en","site_name_ru","event_dates_en","event_dates_ru","venue_en","venue_ru","city_en","city_ru","country_en","country_ru","footer_blurb_en","footer_blurb_ru"])}</div><button className="save">SAVE SETTINGS</button></form></section></div></main>;
}
