import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { logoutAction, saveHero, saveSiteSettings } from "@/app/actions";
import { CollectionEditor } from "@/components/CollectionEditor";

const fields=(row:Record<string,unknown>,names:string[])=>names.map(n=><div className="field" key={n}><label htmlFor={n}>{n.replaceAll("_"," ")}</label>{n.includes("blurb")||n.includes("subtitle")||n.includes("patronage")?<textarea id={n} name={n} defaultValue={String(row[n]??"")}/>:<input id={n} name={n} defaultValue={String(row[n]??"")} required/>}</div>);
export const dynamic="force-dynamic";
export default async function Admin({searchParams}:{searchParams:Promise<{status?:string;collection?:string}>}){
  const user=await requireAdmin(); const database=await db(); const [site,hero,stats,highlights,programmes,speakers,testimonials,tiers,logos,news,ctas,seo,pageSections]=await Promise.all([
    database.prepare("SELECT * FROM site_settings WHERE id=1").first<Record<string,unknown>>(),database.prepare("SELECT * FROM hero WHERE id=1").first<Record<string,unknown>>(),
    database.prepare("SELECT * FROM stats ORDER BY sort_order").all<Record<string,unknown>>(),database.prepare("SELECT * FROM highlights WHERE id=1").all<Record<string,unknown>>(),database.prepare("SELECT * FROM programmes ORDER BY sort_order").all<Record<string,unknown>>(),database.prepare("SELECT * FROM speakers ORDER BY sort_order").all<Record<string,unknown>>(),database.prepare("SELECT * FROM testimonials ORDER BY sort_order").all<Record<string,unknown>>(),database.prepare("SELECT * FROM sponsor_tiers ORDER BY sort_order").all<Record<string,unknown>>(),database.prepare("SELECT * FROM sponsor_logos ORDER BY sort_order").all<Record<string,unknown>>(),database.prepare("SELECT * FROM news_posts ORDER BY published_at DESC").all<Record<string,unknown>>(),database.prepare("SELECT * FROM ctas ORDER BY key").all<Record<string,unknown>>(),database.prepare("SELECT * FROM seo_defaults WHERE id=1").all<Record<string,unknown>>(),database.prepare("SELECT * FROM page_sections ORDER BY sort_order").all<Record<string,unknown>>()
  ]); if(!site||!hero) throw new Error("Seed the CMS first."); const {status,collection}=await searchParams;
  const collections=["site_settings","hero","highlights","stats","programmes","speakers","testimonials","sponsor_tiers","sponsor_logos","news","ctas","seo","page_sections"];
  const cast=(v:{results:Record<string,unknown>[]})=>v.results as never[];
  return <main className="admin-shell"><div className="admin-top"><div><p className="eyebrow">GITEX CMS</p><h1>Content dashboard</h1><small>Signed in as {user.email}</small></div><div><Link href="/en">View site ↗</Link> · <form action={logoutAction} style={{display:"inline"}}><button>Log out</button></form></div></div><div className="admin-grid"><aside className="panel"><h3>Collections</h3><ul className="collection-list">{collections.map(c=><li key={c}><a href={`#collection-${c}`}>{c}</a></li>)}</ul><p><small>All homepage content is editable. Use image/video URLs until R2 uploads are enabled.</small></p></aside><section>{status&&<p className="status">{collection||"Content"} saved. Public pages now use the updated content.</p>}<details className="collection-editor" id="collection-hero" open><summary><span>Hero</span><b>EN + RU</b></summary><form className="panel" action={saveHero}><div className="form-grid">{fields(hero,["eyebrow_en","eyebrow_ru","title_en","title_ru","subtitle_en","subtitle_ru","countdown_target","patronage_line_en","patronage_line_ru"])}</div><button className="save">SAVE HERO</button></form></details><details className="collection-editor" id="collection-site_settings"><summary><span>Site settings</span><b>EN + RU</b></summary><form className="panel" action={saveSiteSettings}><div className="form-grid">{fields(site,["site_name_en","site_name_ru","event_dates_en","event_dates_ru","venue_en","venue_ru","city_en","city_ru","country_en","country_ru","footer_blurb_en","footer_blurb_ru"])}</div><button className="save">SAVE SETTINGS</button></form></details>
  <CollectionEditor name="highlights" title="Highlights & gallery" rows={cast(highlights)} single fields={["title_en","title_ru","body_en","body_ru","video_embed_url","gallery_images_json","factsheet_file_url"]}/>
  <CollectionEditor name="stats" title="Statistics" rows={cast(stats)} fields={["value","label_en","label_ru","suffix","sort_order"]}/>
  <CollectionEditor name="programmes" title="Programmes" rows={cast(programmes)} fields={["slug","title_en","title_ru","body_en","body_ru","image_url","cta_label_en","cta_label_ru","cta_href","sort_order"]}/>
  <CollectionEditor name="speakers" title="Speakers" rows={cast(speakers)} fields={["name_en","name_ru","title_en","title_ru","org_en","org_ru","country_en","country_ru","photo_url","bio_en","bio_ru","sort_order"]}/>
  <CollectionEditor name="testimonials" title="Testimonials" rows={cast(testimonials)} fields={["quote_en","quote_ru","name_en","name_ru","role_en","role_ru","company_en","company_ru","logo_url","sort_order"]}/>
  <CollectionEditor name="sponsor_tiers" title="Sponsor tiers" rows={cast(tiers)} noDelete fields={["name_en","name_ru","sort_order"]}/>
  <CollectionEditor name="sponsor_logos" title="Sponsor logos" rows={cast(logos)} fields={["tier_id","name","image_url","href","sort_order"]}/>
  <CollectionEditor name="news" title="News" rows={cast(news)} fields={["slug","locale","title","excerpt","body_md","cover_url","published_at","seo_json"]}/>
  <CollectionEditor name="ctas" title="CTA blocks" rows={cast(ctas)} noDelete fields={["key","title_en","title_ru","blurb_en","blurb_ru","external_form_url"]}/>
  <CollectionEditor name="seo" title="SEO defaults" rows={cast(seo)} single fields={["title_template_en","title_template_ru","description_en","description_ru","og_image"]}/>
  <CollectionEditor name="page_sections" title="Homepage sections" rows={cast(pageSections)} fields={["section_key","title_en","title_ru","body_en","body_ru","items_json","sort_order"]}/>
  </section></div></main>;
}
