CREATE TABLE IF NOT EXISTS page_sections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  section_key TEXT NOT NULL UNIQUE,
  title_en TEXT NOT NULL,
  title_ru TEXT NOT NULL,
  body_en TEXT NOT NULL DEFAULT '',
  body_ru TEXT NOT NULL DEFAULT '',
  items_json TEXT NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO page_sections(section_key,title_en,title_ru,body_en,body_ru,items_json,sort_order) VALUES
('ecosystem','THE REGION''S FASTEST-GROWING AI ECOSYSTEM','[RU needs review] САМАЯ БЫСТРОРАСТУЩАЯ ИИ-ЭКОСИСТЕМА РЕГИОНА','Aligned with Kazakhstan’s digitalisation and AI ambitions, the inaugural edition brought together global policymakers, AI leaders, tech innovators, investors, and startups—strengthening Central Asia and the Caucasus’ position as an emerging digital powerhouse.','[RU needs review] Первое мероприятие объединило политиков, лидеров ИИ, новаторов, инвесторов и стартапы региона.','[]',10),
('sectors','EXHIBITING SECTORS','[RU needs review] СЕКТОРЫ ВЫСТАВКИ','','','["AI","Cybersecurity","Fintech","Blockchain & Crypto","Cloud & Connectivity","5G & Telecom","Edtech","Healthtech","Smart Cities","Greentech"]',20),
('tracks','7 CONFERENCE TRACKS AT GITEX AI KAZAKHSTAN','[RU needs review] 7 ТЕМ КОНФЕРЕНЦИИ','Converging Policy, Capital, Technology & Enterprise adoption across the Region','[RU needs review] Политика, капитал, технологии и внедрение в бизнесе','[{"title":"AI & Intelligent Infrastructure","body":"From smart farms to AI exports, Kazakhstan’s $5B alem.ai Centre is driving Central Asia’s AI rise.","image":"https://www.gitexcac.com/images/AI_Img.jpg"},{"title":"Data Centers","body":"Kazakhstan is powering a region-wide shift to digital with big-tech infrastructure and progressive policy.","image":"https://www.gitexcac.com/images/data_centers_img.jpg"},{"title":"Industry 4.0","body":"Automation, IoT and digital twins are transforming manufacturing and supply chains.","image":"https://www.gitexcac.com/images/industry_img.jpg"},{"title":"Cybersecurity","body":"Building a secure, adaptive cyber ecosystem to protect critical infrastructure and digital trust.","image":"https://www.gitexcac.com/images/cybersecurity_img.jpg"},{"title":"Smart Energy Transformation","body":"Clean energy and sustainable infrastructure accelerating the region’s green transition.","image":"https://www.gitexcac.com/images/smart_energy_img.jpg"},{"title":"Investment & Innovation","body":"Unlocking global VC flows and positioning the region as a launchpad for innovation.","image":"https://www.gitexcac.com/images/Investment_img.jpg"},{"title":"Future Finance & Digital Assets","body":"A connected regional economy bridging markets across continents.","image":"https://www.gitexcac.com/images/future_finance_img.jpg"}]',30),
('supernova','TAKE THE SPOTLIGHT AND SHOWCASE YOUR STARTUP TO THE WORLD','[RU needs review] ПОКАЖИТЕ СВОЙ СТАРТАП МИРУ','The Supernova Pitch Competition is the definitive platform for startups shaping the future of innovation across Central Asia and the Caucasus.','[RU needs review] Supernova — главная площадка для стартапов, формирующих будущее инноваций региона.','[{"image":"https://www.gitexcac.com/Uploads//Posts/supernova-img-new.jpg"}]',40),
('sponsor_logos','THANK YOU TO OUR 2026 SPONSORS & EXHIBITORS','[RU needs review] СПОНСОРЫ И УЧАСТНИКИ 2026','','','[{"name":"Hikvision","image":"https://www.gitexcac.com/images/HIKVISION.jpg"},{"name":"Yandex","image":"https://www.gitexcac.com/images/Yandex_.png"},{"name":"H3C","image":"https://www.gitexcac.com/images/H3C-up.png"},{"name":"Presight","image":"https://www.gitexcac.com/images/PresightMaster.png"},{"name":"EBRD","image":"https://www.gitexcac.com/images/EBRD_.png?v=1.6"},{"name":"Air Astana","image":"https://www.gitexcac.com/images/air_astana.png"},{"name":"Cloudflare","image":"https://www.gitexcac.com/images/Cloudflarelogonw244.jpg"},{"name":"Visa","image":"https://www.gitexcac.com/images/VISA-up.png"},{"name":"Google Cloud","image":"https://www.gitexcac.com/images/googleCloud_.png"},{"name":"8B World","image":"https://www.gitexcac.com/images/8bworld.png"}]',50),
('tech_partners','TECH TALK PARTNERS','[RU needs review] ПАРТНЕРЫ TECH TALK','','','[{"name":"Cloudflare","image":"https://www.gitexcac.com/Uploads//Posts/logos/Cloudflarelogo17426.jpg"},{"name":"Prosper Pay","image":"https://www.gitexcac.com/Uploads//Posts/logos/Tech/Prosper-Pay.png"},{"name":"EBRD","image":"https://www.gitexcac.com/Uploads//Posts/logos/EBRDlogo17426.jpg"},{"name":"CallCTO","image":"https://www.gitexcac.com/Uploads//Posts/logos/CallCTOlogo17426.jpg"},{"name":"Nexign","image":"https://www.gitexcac.com/Uploads//Posts/logos/Nexignlogo17426.jpg"},{"name":"INNIO","image":"https://www.gitexcac.com/Uploads//Posts/logos/INNIOlogo17426.jpg"},{"name":"Arista","image":"https://www.gitexcac.com/Uploads//Posts/logos/Aristalogo17426.jpg"},{"name":"VinChin","image":"https://www.gitexcac.com/Uploads//Posts/logos/VinChinlogo17426.jpg"},{"name":"Salesforce","image":"https://www.gitexcac.com/Uploads//Posts/logos/Salesforcelogo17426.jpg"},{"name":"Redington","image":"https://www.gitexcac.com/Uploads//Posts/logos/Redingtonlogo17426.jpg"}]',60),
('featured_exhibitors','2026 FEATURED EXHIBITORS','[RU needs review] УЧАСТНИКИ ВЫСТАВКИ 2026','','','[{"name":"Kazakhtelecom","image":"https://www.gitexcac.com/Uploads//Posts/logos/Kaztelekom_%D0%B3%D0%BE%D1%80%D0%B8%D0%B7%D0%BE%D0%BD%D1%82_%D0%B2%D0%B5%D1%80%D1%82%D0%B8%D0%BA.png"},{"name":"Akashi","image":"https://www.gitexcac.com/Uploads//Posts/Ecosystem_Partners/Akashi2.png"},{"name":"Jusan","image":"https://www.gitexcac.com/Uploads//Posts/logos/Jusan_mobile_.jpg"},{"name":"ASBIS","image":"https://www.gitexcac.com/Uploads//Posts/logos/asbis_logo.png"},{"name":"Kcell","image":"https://www.gitexcac.com/Uploads//Posts/logos/kcell_activ5G_.png"},{"name":"Dell Technologies","image":"https://www.gitexcac.com/Uploads//Posts/logos/Dell%20Technologies.jpg"},{"name":"Lenovo","image":"https://www.gitexcac.com/Uploads//Posts/logos/LenovoLogo-POS-Red.png"},{"name":"HP","image":"https://www.gitexcac.com/Uploads//Posts/logos/HPlogo06.jpg"},{"name":"Cisco","image":"https://www.gitexcac.com/Uploads//Posts/logos/CISCO.png"},{"name":"Atlassian","image":"https://www.gitexcac.com/Uploads//Posts/logos/Atlassian.jpg"},{"name":"Noventiq","image":"https://www.gitexcac.com/Uploads//Posts/logos/Noventiqlogo.jpg"},{"name":"QazCloud","image":"https://www.gitexcac.com/Uploads//Posts/logos/QazCloudlogo06.jpg"}]',70);
