ALTER TABLE page_sections ADD COLUMN items_ru_json TEXT NOT NULL DEFAULT '[]';

CREATE TABLE IF NOT EXISTS content_pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  title_en TEXT NOT NULL,
  title_ru TEXT NOT NULL,
  eyebrow_en TEXT NOT NULL DEFAULT '',
  eyebrow_ru TEXT NOT NULL DEFAULT '',
  body_en TEXT NOT NULL DEFAULT '',
  body_ru TEXT NOT NULL DEFAULT '',
  hero_image TEXT,
  sections_json TEXT NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO content_pages(slug,title_en,title_ru,eyebrow_en,eyebrow_ru,body_en,body_ru,hero_image,sections_json,sort_order) VALUES
('about','POWERING THE INTELLIGENCE ECONOMY','ДВИЖУЩАЯ СИЛА ИНТЕЛЛЕКТУАЛЬНОЙ ЭКОНОМИКИ','ABOUT GITEX AI KAZAKHSTAN','О GITEX AI KAZAKHSTAN','GITEX AI Kazakhstan brings government, enterprise, investors, founders and global technology leaders together in Almaty.','GITEX AI Kazakhstan объединяет в Алматы представителей государства, бизнеса, инвесторов, основателей стартапов и мировых технологических лидеров.','https://www.gitexcac.com/images/MAX01827-img.jpg','[{"title_en":"A gateway to Central Asia","title_ru":"Ворота в Центральную Азию","body_en":"Two days of exhibitions, conferences, investment meetings and startup showcases.","body_ru":"Два дня выставок, конференций, инвестиционных встреч и презентаций стартапов."}]',10),
('speakers','GLOBAL MINDS SHAPING THE AI AGENDA','МИРОВЫЕ ЛИДЕРЫ, ФОРМИРУЮЩИЕ ПОВЕСТКУ ИИ','SPEAKERS','СПИКЕРЫ','Meet policymakers, researchers, founders and enterprise leaders advancing the region’s digital future.','Познакомьтесь с политиками, исследователями, основателями и руководителями компаний, создающими цифровое будущее региона.','https://www.gitexcac.com/images/Presidential-Images.jpg','[]',20),
('investors','CONNECTING CAPITAL WITH THE REGION’S BOLDEST FOUNDERS','ОБЪЕДИНЯЕМ КАПИТАЛ С САМЫМИ СМЕЛЫМИ ОСНОВАТЕЛЯМИ РЕГИОНА','INVESTOR PROGRAMME','ПРОГРАММА ДЛЯ ИНВЕСТОРОВ','A curated programme for venture capital, private equity, family offices, angels and corporate investors seeking opportunities across Central Asia and the Caucasus.','Специальная программа для венчурных и частных фондов, семейных офисов, бизнес-ангелов и корпоративных инвесторов, ищущих возможности в Центральной Азии и на Кавказе.','https://www.gitexcac.com/images/Investment_img.jpg','[{"title_en":"Curated meetings","title_ru":"Персональные встречи","body_en":"Meet deal-ready founders and regional co-investment partners.","body_ru":"Встречайтесь с перспективными основателями и региональными партнёрами по совместным инвестициям."},{"title_en":"Market intelligence","title_ru":"Аналитика рынка","body_en":"Hear directly from policymakers and technology leaders.","body_ru":"Получайте информацию напрямую от политиков и технологических лидеров."}]',30),
('executive-meetings-programme','VIP EXECUTIVE MEETINGS','VIP-ВСТРЕЧИ ДЛЯ РУКОВОДИТЕЛЕЙ','INVESTORS','ИНВЕСТОРАМ','Private, pre-qualified meetings connect senior buyers, technology providers and investors.','Закрытые предварительно согласованные встречи объединяют руководителей, поставщиков технологий и инвесторов.','https://www.gitexcac.com/images/MAX00984.jpg','[]',35),
('supernova-pitch-competition','TAKE THE SPOTLIGHT. SHOWCASE YOUR STARTUP TO THE WORLD.','ВЫЙДИТЕ НА СЦЕНУ. ПОКАЖИТЕ СВОЙ СТАРТАП МИРУ.','SUPERNOVA PITCH COMPETITION','КОНКУРС SUPERNOVA PITCH','The region’s most ambitious startups pitch to global investors, accelerators and technology leaders.','Самые амбициозные стартапы региона представляют свои проекты мировым инвесторам, акселераторам и технологическим лидерам.','https://www.gitexcac.com/Uploads//Posts/supernova-img-new.jpg','[{"title_en":"Global exposure","title_ru":"Международная известность","body_en":"Present your solution on a global technology stage.","body_ru":"Представьте своё решение на международной технологической сцене."},{"title_en":"Investor access","title_ru":"Доступ к инвесторам","body_en":"Build relationships with active regional and global investors.","body_ru":"Установите связи с активными региональными и международными инвесторами."}]',40),
('gallery','THIS IS WHAT THE REGION’S LARGEST AI GATHERING LOOKED LIKE','ТАК ПРОШЛА КРУПНЕЙШАЯ В РЕГИОНЕ ВСТРЕЧА, ПОСВЯЩЁННАЯ ИИ','GALLERY','ГАЛЕРЕЯ','Explore moments from GITEX AI Kazakhstan: landmark announcements, packed exhibition halls and global collaboration.','Посмотрите яркие моменты GITEX AI Kazakhstan: важные объявления, заполненные выставочные залы и международное сотрудничество.','https://www.gitexcac.com/images/VM_09775.jpg','[]',50),
('cybersecurity','BUILDING DIGITAL TRUST ACROSS THE REGION','СОЗДАЁМ ЦИФРОВОЕ ДОВЕРИЕ ВО ВСЁМ РЕГИОНЕ','CYBERSECURITY','КИБЕРБЕЗОПАСНОСТЬ','Cybersecurity leaders examine resilient infrastructure, threat intelligence, cloud security and the policies protecting a rapidly expanding digital economy.','Лидеры кибербезопасности обсуждают устойчивую инфраструктуру, анализ угроз, облачную безопасность и политику защиты быстрорастущей цифровой экономики.','https://www.gitexcac.com/images/cybersecurity_img.jpg','[{"title_en":"Critical infrastructure","title_ru":"Критическая инфраструктура","body_en":"Strategies for securing essential national and enterprise systems.","body_ru":"Стратегии защиты важнейших государственных и корпоративных систем."},{"title_en":"Adaptive defence","title_ru":"Адаптивная защита","body_en":"Practical intelligence for a fast-changing threat landscape.","body_ru":"Практические решения для быстро меняющегося ландшафта угроз."}]',60),
('terms-and-conditions','TERMS AND CONDITIONS','УСЛОВИЯ ИСПОЛЬЗОВАНИЯ','LEGAL','ПРАВОВАЯ ИНФОРМАЦИЯ','These mockup terms describe use of the demonstration website. Production legal copy must be reviewed and approved by the event owner before launch.','Эти демонстрационные условия описывают использование макета сайта. Перед запуском юридический текст должен быть проверен и утверждён владельцем мероприятия.','', '[]',90),
('privacy-policy','PRIVACY POLICY','ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ','LEGAL','ПРАВОВАЯ ИНФОРМАЦИЯ','This demonstration does not submit registration forms or collect marketing data. Production privacy wording and consent integrations require client approval.','Этот демонстрационный сайт не отправляет регистрационные формы и не собирает маркетинговые данные. Для запуска необходимы утверждённые клиентом политика конфиденциальности и механизмы согласия.','', '[]',91),
('cookie-policy','COOKIE POLICY','ПОЛИТИКА COOKIE','LEGAL','ПРАВОВАЯ ИНФОРМАЦИЯ','Essential preferences are stored locally to remember the cookie-banner choice. Analytics and advertising cookies are not enabled in this mockup.','Локально сохраняются только необходимые настройки, включая выбор в баннере cookie. Аналитические и рекламные cookie в этом макете не используются.','', '[]',92);

UPDATE site_settings SET site_name_ru=REPLACE(site_name_ru,'[RU needs review] ',''),event_dates_ru=REPLACE(event_dates_ru,'[RU needs review] ',''),venue_ru=REPLACE(venue_ru,'[RU needs review] ',''),city_ru=REPLACE(city_ru,'[RU needs review] ',''),country_ru=REPLACE(country_ru,'[RU needs review] ',''),footer_blurb_ru=REPLACE(footer_blurb_ru,'[RU needs review] ',''),legal_links_json=REPLACE(legal_links_json,'[RU needs review] ','');
UPDATE hero SET eyebrow_ru=REPLACE(eyebrow_ru,'[RU needs review] ',''),title_ru=REPLACE(title_ru,'[RU needs review] ',''),subtitle_ru=REPLACE(subtitle_ru,'[RU needs review] ',''),patronage_line_ru=REPLACE(patronage_line_ru,'[RU needs review] ',''),primary_ctas_json=REPLACE(primary_ctas_json,'[RU needs review] ','');
UPDATE stats SET label_ru=REPLACE(label_ru,'[RU needs review] ','');
UPDATE highlights SET title_ru=REPLACE(title_ru,'[RU needs review] ',''),body_ru=REPLACE(body_ru,'[RU needs review] ','');
UPDATE programmes SET title_ru=REPLACE(title_ru,'[RU needs review] ',''),body_ru=REPLACE(body_ru,'[RU needs review] ',''),cta_label_ru=REPLACE(cta_label_ru,'[RU needs review] ','');
UPDATE speakers SET name_ru=REPLACE(name_ru,'[RU needs review] ',''),title_ru=REPLACE(title_ru,'[RU needs review] ',''),org_ru=REPLACE(org_ru,'[RU needs review] ',''),country_ru=REPLACE(country_ru,'[RU needs review] ',''),bio_ru=REPLACE(COALESCE(bio_ru,''),'[RU needs review] ','');
UPDATE testimonials SET quote_ru=REPLACE(quote_ru,'[RU needs review] ',''),name_ru=REPLACE(name_ru,'[RU needs review] ',''),role_ru=REPLACE(role_ru,'[RU needs review] ',''),company_ru=REPLACE(company_ru,'[RU needs review] ','');
UPDATE sponsor_tiers SET name_ru=REPLACE(name_ru,'[RU needs review] ','');
UPDATE news_posts SET title=REPLACE(title,'[RU needs review] ',''),excerpt=REPLACE(excerpt,'[RU needs review] ',''),body_md=REPLACE(body_md,'[RU needs review] ','') WHERE locale='ru';
UPDATE ctas SET title_ru=REPLACE(title_ru,'[RU needs review] ',''),blurb_ru=REPLACE(blurb_ru,'[RU needs review] ','');
UPDATE seo_defaults SET title_template_ru=REPLACE(title_template_ru,'[RU needs review] ',''),description_ru=REPLACE(description_ru,'[RU needs review] ','');
UPDATE page_sections SET title_ru=REPLACE(title_ru,'[RU needs review] ',''),body_ru=REPLACE(body_ru,'[RU needs review] ','');

UPDATE page_sections SET items_ru_json='["Искусственный интеллект","Кибербезопасность","Финтех","Блокчейн и криптовалюты","Облака и связь","5G и телеком","Образовательные технологии","Медицинские технологии","Умные города","Зелёные технологии"]' WHERE section_key='sectors';
UPDATE page_sections SET items_ru_json='[{"title":"ИИ и интеллектуальная инфраструктура","body":"От умного сельского хозяйства до экспорта ИИ — Казахстан ускоряет развитие технологий в Центральной Азии.","image":"https://www.gitexcac.com/images/AI_Img.jpg"},{"title":"Центры обработки данных","body":"Казахстан развивает цифровую инфраструктуру региона при поддержке прогрессивной политики.","image":"https://www.gitexcac.com/images/data_centers_img.jpg"},{"title":"Индустрия 4.0","body":"Автоматизация, IoT и цифровые двойники меняют производство и цепочки поставок.","image":"https://www.gitexcac.com/images/industry_img.jpg"},{"title":"Кибербезопасность","body":"Безопасная и адаптивная киберэкосистема защищает инфраструктуру и цифровое доверие.","image":"https://www.gitexcac.com/images/cybersecurity_img.jpg"},{"title":"Умная энергетика","body":"Чистая энергия и устойчивая инфраструктура ускоряют зелёный переход.","image":"https://www.gitexcac.com/images/smart_energy_img.jpg"},{"title":"Инвестиции и инновации","body":"Международный капитал превращает регион в платформу для инноваций.","image":"https://www.gitexcac.com/images/Investment_img.jpg"},{"title":"Финансы будущего и цифровые активы","body":"Связанная региональная экономика объединяет рынки разных континентов.","image":"https://www.gitexcac.com/images/future_finance_img.jpg"}]' WHERE section_key='tracks';
