"use client";
import { useState } from "react";
type Programme={title:string;body:string;image:string;slug:string};
const logos=["NSStartupsXAIlogo1802.png","AIxKazakhstanlogo1802.png","GCValleylogoasia1802.png","GGimpactlogo1802.png"];
export function ProgrammeExperience({programmes,locale}:{programmes:Programme[];locale:"en"|"ru"}){
 const fallback=programmes[0]; const display=Array.from({length:4},(_,i)=>programmes[i]||fallback); const [active,setActive]=useState(0); const p=display[active]; if(!p)return null;
 const isNorth=active===0,isCyber=active===2;
 const primaryLabel=isNorth?(locale==="en"?"EXPLORE THE PROGRAMME":"О ПРОГРАММЕ"):isCyber?(locale==="en"?"LEARN MORE":"ПОДРОБНЕЕ"):(locale==="en"?"BOOK A SPACE":"ЗАБРОНИРОВАТЬ МЕСТО");
 const select=(index:number)=>setActive(index);
 return <><div className="programme-tabs" role="tablist" aria-label={locale==="en"?"Flagship programmes":"Флагманские программы"}>{display.map((item,i)=><button id={`programme-tab-${i}`} role="tab" aria-controls="programme-panel" aria-selected={active===i} tabIndex={active===i?0:-1} className={active===i?"active":""} onClick={()=>select(i)} onKeyDown={e=>{if(e.key==="ArrowRight")select((i+1)%4);if(e.key==="ArrowLeft")select((i+3)%4)}} key={`${item.slug}-${i}`}><img src={`https://www.gitexcac.com/contents/Theme-2025/images/${logos[i]}`} alt={item.title}/></button>)}</div><div id="programme-panel" role="tabpanel" aria-labelledby={`programme-tab-${active}`} className={`programme-stage programme-theme-${active}`}><div><p className="programme-index">0{active+1}</p><h3>{p.title}</h3><div className="programme-body">{p.body.split("\n").filter(Boolean).map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div>{isNorth&&<div className="mini-stats"><b>300+<small>{locale==="en"?"AWARD WINNING STARTUPS":"СТАРТАПОВ"}</small></b><b>150+<small>{locale==="en"?"ACTIVE INVESTORS":"ИНВЕСТОРОВ"}</small></b><b>20+<small>{locale==="en"?"COUNTRIES":"СТРАН"}</small></b></div>}{(isNorth||isCyber)&&<div className="programme-details"><details><summary>{isCyber?(locale==="en"?"GITEX CISCO NETWORKING LOUNGE":"СЕТЕВАЯ ЗОНА GITEX CISCO"):(locale==="en"?"SUPERNOVA PITCH COMPETITION":"КОНКУРС SUPERNOVA PITCH")}</summary></details><details><summary>{isCyber?(locale==="en"?"CYBERSECURITY TRACK":"ТРЕК КИБЕРБЕЗОПАСНОСТИ"):(locale==="en"?"CONNECT WITH 150+ INVESTORS":"ВСТРЕЧИ СО 150+ ИНВЕСТОРАМИ")}</summary></details></div>}<div className="programme-actions"><a href={isNorth?`/${locale}/supernova-pitch-competition`:`/${locale}/${isCyber?"cybersecurity":"about"}`}>{primaryLabel}</a><a href="#register">{locale==="en"?"REGISTER TO VISIT":"ЗАРЕГИСТРИРОВАТЬСЯ"}</a></div></div><img key={`${p.image}-${active}`} src={p.image} alt=""/></div></>;
}
