PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO site_settings VALUES (1,'GITEX AI Kazakhstan','[RU needs review] GITEX AI Казахстан','en','7–8 June 2027','[RU needs review] 7–8 июня 2027','Atakent Exhibition Centre','[RU needs review] Выставочный центр «Атакент»','Almaty','Алматы','Kazakhstan','Казахстан','https://www.gitexcac.com/assets/logo.svg',NULL,'[{"label":"LinkedIn","href":"https://linkedin.com"},{"label":"Instagram","href":"https://instagram.com"}]','Powering the intelligence economy of Central Asia & the Caucasus.','[RU needs review] Развиваем интеллектуальную экономику Центральной Азии и Кавказа.','[{"label":{"en":"Privacy","ru":"[RU needs review] Конфиденциальность"},"href":"#"}]',CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO hero VALUES (1,'THE REGION’S MOST EMPOWERING TECH EVENT','[RU needs review] ГЛАВНОЕ ТЕХНОЛОГИЧЕСКОЕ СОБЫТИЕ РЕГИОНА','POWERING THE INTELLIGENCE ECONOMY','[RU needs review] ДВИЖУЩАЯ СИЛА ИНТЕЛЛЕКТУАЛЬНОЙ ЭКОНОМИКИ','OF CENTRAL ASIA & THE CAUCASUS','[RU needs review] ЦЕНТРАЛЬНОЙ АЗИИ И КАВКАЗА','2027-06-07T09:00:00+05:00','UNDER THE HIGH PATRONAGE OF THE PRESIDENT H.E. KASSYM-JOMART TOKAYEV','[RU needs review] ПОД ВЫСОКИМ ПАТРОНАЖЕМ ПРЕЗИДЕНТА К.-Ж. ТОКАЕВА','[{"label":{"en":"PRE-REGISTER TO VISIT","ru":"[RU needs review] РЕГИСТРАЦИЯ"},"href":"#register","style":"primary"},{"label":{"en":"BOOK A STAND","ru":"[RU needs review] ЗАБРОНИРОВАТЬ СТЕНД"},"href":"#exhibit","style":"outline"}]','[]','[]',CURRENT_TIMESTAMP);

DELETE FROM stats; INSERT INTO stats(value,label_en,label_ru,suffix,sort_order) VALUES ('30000','VISITORS','[RU needs review] ПОСЕТИТЕЛЕЙ','+',1),('300','EXHIBITORS','[RU needs review] ЭКСПОНЕНТОВ','+',2),('2500','C-LEVEL ATTENDEES','[RU needs review] РУКОВОДИТЕЛЕЙ','+',3),('150','INVESTORS','[RU needs review] ИНВЕСТОРОВ','+',4),('60','COUNTRIES','[RU needs review] СТРАН','',5);
INSERT OR REPLACE INTO highlights VALUES (1,'THE WORLD CAME TO ALMATY. THE FUTURE FOLLOWED','[RU needs review] МИР ПРИЕХАЛ В АЛМАТЫ. БУДУЩЕЕ — СЛЕДОМ.','Together, we launched a new era for AI, innovation, and global collaboration in Central Asia. See you again in 2027.','[RU needs review] Вместе мы открыли новую эру ИИ, инноваций и международного сотрудничества в Центральной Азии. До встречи в 2027 году.','https://www.youtube.com/embed/dQw4w9WgXcQ','[]','#factsheet');

DELETE FROM programmes; INSERT INTO programmes(slug,title_en,title_ru,body_en,body_ru,image_url,cta_label_en,cta_label_ru,cta_href,sort_order) VALUES
('north-star','NORTH STAR KAZAKHSTAN','[RU needs review] NORTH STAR КАЗАХСТАН','Central Asia’s leading startup exhibition, connecting founders, accelerators and investors.','[RU needs review] Ведущая стартап-выставка Центральной Азии для основателей, акселераторов и инвесторов.',NULL,'LEARN MORE','[RU needs review] ПОДРОБНЕЕ','#startup',1),
('investor-programme','INVESTOR PROGRAMME','[RU needs review] ПРОГРАММА ДЛЯ ИНВЕСТОРОВ','A curated platform connecting VCs, angels and corporate investors with deal-ready startups.','[RU needs review] Платформа, объединяющая венчурные фонды и корпоративных инвесторов с перспективными стартапами.',NULL,'JOIN THE PROGRAMME','[RU needs review] ПРИСОЕДИНИТЬСЯ','#investor',2),
('conference','7 CONFERENCE TRACKS','[RU needs review] 7 ТРЕКОВ КОНФЕРЕНЦИИ','Policy, capital, technology and enterprise adoption converge across the region.','[RU needs review] Политика, капитал, технологии и внедрение в бизнесе объединяются на одной площадке.',NULL,'EXPLORE','[RU needs review] СМОТРЕТЬ','#programmes',3);

DELETE FROM speakers; INSERT INTO speakers(name_en,name_ru,title_en,title_ru,org_en,org_ru,country_en,country_ru,photo_url,bio_en,bio_ru,sort_order) VALUES
('H.E. Zhaslan Madiyev','[RU needs review] Жаслан Мадиев','Deputy Prime Minister & Minister of AI and Digital Development','[RU needs review] Заместитель Премьер-министра — Министр ИИ и цифрового развития','Republic of Kazakhstan','Республика Казахстан','Kazakhstan','Казахстан',NULL,NULL,NULL,1),
('Dr. Kai-Fu Lee','[RU needs review] Доктор Кай-Фу Ли','Chairman & Chief Executive Officer','[RU needs review] Председатель и генеральный директор','01.AI & Sinovation Ventures','01.AI & Sinovation Ventures','China','Китай',NULL,NULL,NULL,2),
('Lambert Hogenhout','[RU needs review] Ламберт Хогенхаут','Chief Data and AI','[RU needs review] Руководитель по данным и ИИ','United Nations','Организация Объединённых Наций','United States','США',NULL,NULL,NULL,3);

DELETE FROM testimonials; INSERT INTO testimonials(quote_en,quote_ru,name_en,name_ru,role_en,role_ru,company_en,company_ru,logo_url,sort_order) VALUES
('GITEX AI Kazakhstan connects us with visionary partners and accelerates our mission to build resilient, future-ready digital infrastructure.','[RU needs review] GITEX AI Kazakhstan связывает нас с дальновидными партнёрами и ускоряет создание устойчивой цифровой инфраструктуры.','Alnur Yermagambetov','[RU needs review] Алнур Ермагамбетов','Head of Department','[RU needs review] Руководитель департамента','Lenovo EECA','Lenovo EECA',NULL,1),
('The event is an ideal platform to engage with regional customers and partners.','[RU needs review] Это идеальная платформа для взаимодействия с клиентами и партнёрами региона.','Gary Huang','[RU needs review] Гэри Хуанг','Co-President','[RU needs review] Сопрезидент','H3C','H3C',NULL,2);

DELETE FROM sponsor_logos; DELETE FROM sponsor_tiers; INSERT INTO sponsor_tiers(id,name_en,name_ru,sort_order) VALUES (1,'STRATEGIC SPONSORS','[RU needs review] СТРАТЕГИЧЕСКИЕ СПОНСОРЫ',1),(2,'FEATURED EXHIBITORS','[RU needs review] КЛЮЧЕВЫЕ ЭКСПОНЕНТЫ',2); INSERT INTO sponsor_logos(tier_id,name,image_url,href,sort_order) VALUES (1,'Huawei',NULL,'https://www.huawei.com',1),(1,'Presight',NULL,'https://www.presight.ai',2),(2,'Lenovo',NULL,'https://www.lenovo.com',1),(2,'H3C',NULL,'https://www.h3c.com',2);

DELETE FROM news_posts; INSERT INTO news_posts(slug,locale,title,excerpt,body_md,cover_url,published_at,seo_json) VALUES
('gitex-ai-kazakhstan-returns','en','GITEX AI Kazakhstan returns to Almaty in 2027','The region’s technology community will reunite in Almaty on 7–8 June 2027.','# GITEX AI Kazakhstan returns\n\nThe next edition will build on the momentum of the inaugural gathering.',NULL,'2026-08-20T09:00:00Z','{"description":"GITEX AI Kazakhstan 2027 announcement"}'),
('gitex-ai-kazakhstan-returns','ru','[RU needs review] GITEX AI Kazakhstan возвращается в Алматы в 2027 году','[RU needs review] Технологическое сообщество региона вновь встретится 7–8 июня 2027 года.','# GITEX AI Kazakhstan возвращается\n\n[RU needs review] Следующая выставка продолжит успех первого события.',NULL,'2026-08-20T09:00:00Z','{}'),
('ai-ecosystem','en','Kazakhstan’s AI ecosystem enters a new era','Global policymakers, founders and investors are accelerating regional digital growth.','# A new era\n\nCentral Asia is emerging as a global digital powerhouse.',NULL,'2026-07-14T09:00:00Z','{}'),
('ai-ecosystem','ru','[RU needs review] Экосистема ИИ Казахстана вступает в новую эпоху','[RU needs review] Политики, основатели и инвесторы ускоряют цифровой рост региона.','# Новая эпоха\n\n[RU needs review] Центральная Азия становится цифровым центром.',NULL,'2026-07-14T09:00:00Z','{}'),
('investor-programme-2027','en','Investor programme opens expressions of interest','VCs, angels and corporate investors can now register their interest.','# Investor programme\n\nMeet deal-ready founders from across the region.',NULL,'2026-06-30T09:00:00Z','{}'),
('investor-programme-2027','ru','[RU needs review] Открыт приём заявок в программу для инвесторов','[RU needs review] Венчурные и корпоративные инвесторы могут зарегистрировать интерес.','# Программа для инвесторов\n\n[RU needs review] Познакомьтесь с перспективными основателями региона.',NULL,'2026-06-30T09:00:00Z','{}');

DELETE FROM ctas; INSERT INTO ctas VALUES ('registerVisit','PRE-REGISTER TO VISIT','[RU needs review] РЕГИСТРАЦИЯ','Join the region’s largest AI gathering.','[RU needs review] Присоединяйтесь к крупнейшей встрече лидеров ИИ в регионе.','#register'),('exhibit','EXHIBIT WITH US','[RU needs review] СТАТЬ ЭКСПОНЕНТОМ','Showcase your technology to buyers and decision-makers.','[RU needs review] Представьте свои технологии покупателям и лидерам отрасли.','#exhibit'),('investor','JOIN THE INVESTOR PROGRAMME','[RU needs review] ПРОГРАММА ДЛЯ ИНВЕСТОРОВ','Meet deal-ready startups and co-investment partners.','[RU needs review] Встречайтесь со стартапами и партнёрами по инвестициям.','#investor'),('startup','SHOWCASE YOUR STARTUP','[RU needs review] ПРЕДСТАВЬТЕ СВОЙ СТАРТАП','Take the spotlight at the Supernova Pitch Competition.','[RU needs review] Выступите на конкурсе Supernova Pitch.','#startup');
INSERT OR REPLACE INTO seo_defaults VALUES (1,'%s | GITEX AI Kazakhstan','%s | GITEX AI Казахстан','The region’s most empowering tech, startup and digital investment event.','[RU needs review] Главное событие региона в сфере технологий, стартапов и цифровых инвестиций.',NULL);

INSERT OR IGNORE INTO admin_users(email,password_hash) VALUES ('admin@gitex.local','pbkdf2_sha256$210000$XpGYR4cxgn+GmmWAdVr5aA==$Ly9F41j2dkmqtDJuXV8Sq7r343GEmrJ/1FNCovcK69Q=');

-- Reference-site media URLs. Images remain CMS-owned URLs and videos remain embeds.
UPDATE site_settings SET logo_url='https://www.gitexcac.com/images/logocac-New.png' WHERE id=1;
UPDATE hero SET primary_ctas_json='[{"label":{"en":"BOOK A STAND","ru":"[RU needs review] ЗАБРОНИРОВАТЬ СТЕНД"},"href":"#exhibit","style":"red"},{"label":{"en":"BOOK A POD","ru":"[RU needs review] ЗАБРОНИРОВАТЬ ПОД"},"href":"#investors","style":"cyan"},{"label":{"en":"PRE-REGISTER TO VISIT","ru":"[RU needs review] РЕГИСТРАЦИЯ"},"href":"#register","style":"primary"}]' WHERE id=1;
UPDATE highlights SET video_embed_url='https://www.youtube.com/embed/hbnw0UdSQeA?autoplay=1&mute=1&loop=1&controls=0&playlist=hbnw0UdSQeA', gallery_images_json='["https://www.gitexcac.com/images/Presidential-Images.jpg","https://www.gitexcac.com/images/VM_09775.jpg","https://www.gitexcac.com/images/MAX00984.jpg","https://www.gitexcac.com/images/VM_01145.jpg","https://www.gitexcac.com/images/img_0022.jpg","https://www.gitexcac.com/images/MAX01827.jpg"]' WHERE id=1;
UPDATE programmes SET image_url=CASE slug WHEN 'north-star' THEN 'https://www.gitexcac.com/contents/Theme-2025/images/GACASIAthumb0502.jpg' WHEN 'investor-programme' THEN 'https://www.gitexcac.com/images/MAX01827-img.jpg' ELSE 'https://www.gitexcac.com/images/Ai-council-Meeting.jpg' END;
UPDATE speakers SET photo_url=CASE name_en WHEN 'H.E. Zhaslan Madiyev' THEN 'https://www.gitexcac.com/Uploads//Posts/Speakers/Speaker_1.jpg.jpeg' WHEN 'Dr. Kai-Fu Lee' THEN 'https://www.gitexcac.com/Uploads//Posts/Kai-Fu%20Lee.jpg' ELSE 'https://www.gitexcac.com/Uploads//Posts/Speakers/Lambert%20Hogenhout.jpg' END;
UPDATE sponsor_logos SET image_url=CASE name WHEN 'Huawei' THEN 'https://www.gitexcac.com/images/HW_POS_RGB.png' WHEN 'Presight' THEN 'https://www.gitexcac.com/images/PresightMaster.png' WHEN 'Lenovo' THEN 'https://www.gitexcac.com/images/LenovoLogo-POS-Red.png' ELSE 'https://www.gitexcac.com/images/H3C-up.png' END;
