import { notFound } from "next/navigation";
import { getHomepage, json, localized, type Locale } from "@/lib/db";
import { AnimatedCounter } from "@/components/AnimatedCounter";
import { SiteHeader } from "@/components/SiteHeader";
import { HomeExperience } from "@/components/HomeExperience";
import { ProgrammeExperience } from "@/components/ProgrammeExperience";
import { ScrollCarousel } from "@/components/ScrollCarousel";
import { TestimonialsCarousel } from "@/components/TestimonialsCarousel";

type CTA={label:{en:string;ru:string};href:string;style:string};
export const dynamic="force-dynamic";
export default async function Home({params}:{params:Promise<{locale:string}>}){
  const {locale:raw}=await params; if(raw!=="en"&&raw!=="ru") notFound(); const locale=raw as Locale;
  const d=await getHomepage(locale); const h=d.hero,s=d.settings,x=d.highlights; const ct=json<CTA[]>(h.primary_ctas_json,[]); const gallery=json<string[]>(x.gallery_images_json,[]);
  const section=(key:string)=>d.sections.find(v=>v.section_key===key)!;
  const items=<T,>(key:string)=>json<T[]>(locale==="ru"&&section(key)?.items_ru_json!=="[]"?section(key)?.items_ru_json:section(key)?.items_json,[]);
  const ecosystem=section("ecosystem"), president=section("president"), government=section("government"), sectors=section("sectors"), tracks=section("tracks"), supernova=section("supernova"), network=section("network");
  return <main><HomeExperience locale={locale}/>
    <SiteHeader locale={locale} logo={String(s.logo_url)}/>
    <section className="hero"><div className="hero-video"><iframe src="https://www.youtube.com/embed/L06Z9x9Fst4?autoplay=1&mute=1&loop=1&controls=0&modestbranding=1&playsinline=1&rel=0&playlist=L06Z9x9Fst4" title="GITEX AI Kazakhstan" allow="autoplay; encrypted-media"/></div><div className="hero-wash"/><div id="top" className="hero-copy"><img className="lockup" src={String(s.logo_url)} alt="GITEX AI Central Asia & Caucasus Kazakhstan"/><p className="patronage">{localized(h,"patronage_line",locale)}</p><h1>{localized(h,"title",locale)}</h1><h2>{localized(h,"subtitle",locale)}</h2><p className="hero-description">{localized(h,"eyebrow",locale)}</p><div className="actions">{ct.map((c,i)=><a className={c.style} href={c.href} key={i}>{c.label[locale]}</a>)}</div></div><div className="social-rail"><a href="https://www.linkedin.com/company/gitexaikazakhstan/" aria-label="LinkedIn">in</a><a href="https://www.instagram.com/gitexaikazakhstan/" aria-label="Instagram">◎</a><a href="https://www.facebook.com/gitexaikazakhstan" aria-label="Facebook">f</a><a href="https://www.youtube.com/@GITEXCENTRALASIACAUCASUS" aria-label="YouTube">▶</a><a href="https://t.me/gitexaikazakhstan" aria-label="Telegram">➤</a></div></section>
    <section className="gallery"><h2>{locale==="en"?<>THE LARGEST AI GATHERING IN THE REGION<br/>THIS IS WHAT IT LOOKED LIKE</>:<>КРУПНЕЙШАЯ В РЕГИОНЕ ВСТРЕЧА ОБ ИИ<br/>ТАК ЭТО БЫЛО</>}</h2><div className="gallery-strip">{gallery.slice(0,6).map((url,i)=><img src={url} alt={`GITEX highlight ${i+1}`} key={url}/>)}</div><div className="gallery-actions"><a href={`/${locale}/gallery`}>{locale==="en"?"SEE MORE":"СМОТРЕТЬ ЕЩЁ"}</a><a id="factsheet" href={String(x.factsheet_file_url)}>{locale==="en"?"DOWNLOAD FACTSHEET":"СКАЧАТЬ ОТЧЁТ"}</a></div></section>
    <section className="highlight-video"><iframe src={String(x.video_embed_url)} title="GITEX AI Kazakhstan highlights" allow="autoplay; encrypted-media"/><h2>WATCH THE HIGHLIGHTS OF<br/>GITEX AI KAZAKHSTAN 2026</h2></section>
    <section className="statement"><p>{localized(x,"title",locale)}</p><h2>{localized(x,"body",locale)}</h2></section>
    <section className="stats-wrap"><h2>THE REGION&apos;S MOST EMPOWERING TECH, STARTUP &amp; DIGITAL<br/>INVESTMENT EVENT CONVERGING POWERFUL ALLIANCES<br/>ACROSS BUSINESS, CAPITAL &amp; POLICY</h2><div className="stats">{d.stats.map((item)=><article key={String(item.id)}><AnimatedCounter value={String(item.value)} suffix={String(item.suffix??"")}/><span>{localized(item,"label",locale)}</span></article>)}</div></section>
    <section className="intro"><div><p className="eyebrow">{localized(ecosystem,"title",locale)}</p><h2>POWERFUL ALLIANCES ACROSS<br/>BUSINESS, CAPITAL &amp; POLICY</h2><p>{localized(ecosystem,"body",locale)}</p><a href="#register">GET INVOLVED</a></div></section>
    <section className="feature-panel president"><div><h2>{localized(president,"title",locale)}</h2><p>{localized(president,"body",locale)}</p><a href="https://www.gitexcac.com/section">READ MORE</a></div><img src={items<{image:string}>("president")[0]?.image} alt="AI Development Council meeting"/></section>
    <section className="testimonials"><h2>{locale==="en"?"TESTIMONIALS":"ОТЗЫВЫ"}</h2><TestimonialsCarousel items={d.testimonials.map(t=>({quote:localized(t,"quote",locale),name:localized(t,"name",locale),role:localized(t,"role",locale),company:localized(t,"company",locale),logo:String(t.logo_url||""),image:String(t.image_url||"")}))}/></section>
    <section className="government"><video autoPlay muted loop playsInline src={items<{video:string}>("government")[0]?.video}/><div><div className="government-heading"><h2>{localized(government,"title",locale)}</h2><p>{localized(government,"body",locale)}</p></div><div className="government-card"><div><span className="government-mark">“</span><p>{locale==="en"?"Hosting GITEX in Almaty confirms Kazakhstan’s growing role as a regional hub for technology leaders, startups, and investment. For us, this is not just a large-scale event, but a practical instrument to accelerate digital transformation and the adoption of artificial intelligence across the economy and public administration.":"Проведение GITEX в Алматы подтверждает растущую роль Казахстана как регионального центра технологий, стартапов и инвестиций. Это практический инструмент ускорения цифровой трансформации и внедрения искусственного интеллекта."}</p><b>{items<{name:string}>("government")[0]?.name}</b><small>{locale==="en"?"Deputy Prime Minister & Minister of Artificial Intelligence & Digital Development of the Republic of Kazakhstan":"Заместитель Премьер-министра и Министр искусственного интеллекта и цифрового развития Республики Казахстан"}</small><img className="ministry-logo" src="https://www.gitexcac.com/Uploads//Posts/ai_digital_3.png" alt="AI & Digital Ministry"/></div><img className="government-person" src="https://www.gitexcac.com/Uploads//Posts/quote_img.jpg" alt="H.E. Zhaslan Madiyev"/></div></div></section>
    <section id="programmes" className="programmes"><div className="programme-heading"><h2>{locale==="en"?"FLAGSHIP PROGRAMMES & LIVE EXPERIENCES":"ФЛАГМАНСКИЕ ПРОГРАММЫ И ЯРКИЕ СОБЫТИЯ"}</h2><p>{locale==="en"?"Where startups, investors, AI and sustainability collide.":"Место встречи стартапов, инвесторов, ИИ и устойчивых технологий."}</p></div><ProgrammeExperience locale={locale} programmes={d.programmes.map(p=>({slug:String(p.slug),title:localized(p,"title",locale),body:localized(p,"body",locale),image:String(p.image_url)}))}/></section>
    <section id="speakers" className="section dark"><p className="eyebrow">{locale==="en"?"GLOBAL MINDS":"МИРОВЫЕ ЛИДЕРЫ"}</p><h2>{locale==="en"?"Putting the nation’s AI agenda forward":"Развивая национальную повестку в сфере ИИ"}</h2><ScrollCarousel>{d.speakers.map(p=><article className="speaker-slide" key={String(p.id)}><div className="portrait" style={{backgroundImage:`url(${String(p.photo_url||"")})`}}/><small>{localized(p,"country",locale)}</small><h3>{localized(p,"name",locale)}</h3><p>{localized(p,"title",locale)}</p><b>{localized(p,"org",locale)}</b></article>)}</ScrollCarousel><a className="view-all" href={`/${locale}/speakers`}>{locale==="en"?"VIEW ALL SPEAKERS":"ВСЕ СПИКЕРЫ"}</a></section>
    <section id="exhibition" className="sectors"><h2>{localized(sectors,"title",locale)}</h2><div>{items<string>("sectors").map((v,i)=><article key={v}><span>{String(i+1).padStart(2,"0")}</span><h3>{v}</h3></article>)}</div></section>
    <section id="themes" className="tracks"><p className="eyebrow">{localized(tracks,"body",locale)}</p><h2>{localized(tracks,"title",locale)}</h2><div>{items<{title:string;body:string;image:string}>("tracks").map(v=><article key={v.title}><img src={v.image} alt=""/><div><h3>{v.title}</h3><p>{v.body}</p></div></article>)}</div><a className="primary" href="#register">PRE-REGISTER TO VISIT</a></section>
    <section id="startup" className="supernova"><div><h2>{localized(supernova,"title",locale)}</h2><p>{localized(supernova,"body",locale)}</p><a href={`/${locale}/supernova-pitch-competition`}>{locale==="en"?"LEARN MORE":"ПОДРОБНЕЕ"}</a></div><img src={items<{image:string}>("supernova")[0]?.image} alt="Supernova pitch competition"/></section>
    {["sponsor_logos","tech_partners","featured_exhibitors"].map(key=>{const sec=section(key);return <section id={key==="sponsor_logos"?"sponsors":undefined} className={`logo-band ${key}`} key={key}><h2>{localized(sec,"title",locale)}</h2><div>{items<{name:string;image:string}>(key).map(v=><figure key={v.name}><img src={v.image} alt={v.name}/></figure>)}</div></section>})}
    <section className="section news"><p className="eyebrow">{locale==="en"?"NEWSROOM":"НОВОСТИ"}</p><div className="cards">{d.news.map(n=><article className="card" key={String(n.id)}><small>{new Date(String(n.published_at)).toLocaleDateString(locale)}</small><h3>{String(n.title)}</h3><p>{String(n.excerpt)}</p><a href={`/${locale}/news/${n.slug}`}>{locale==="en"?"VIEW MORE":"ПОДРОБНЕЕ"}</a></article>)}</div></section>
    {["ecosystem_partners","media_partners"].map(key=>{const sec=section(key);return <section className={`logo-band ${key}`} key={key}><h2>{localized(sec,"title",locale)}</h2><div>{items<{name:string;image:string}>(key).map(v=><figure key={v.name}><img src={v.image} alt={v.name}/></figure>)}</div></section>})}
    <section className="network"><h2>{localized(network,"title",locale)}</h2><img src={items<{image:string}>("network")[0]?.image} alt="GITEX global technology network"/></section>
    <footer className="site-footer"><div className="footer-brand"><img src={String(s.logo_url)} alt="GITEX AI Kazakhstan"/><span className="newsletter">{locale==="en"?"SIGN UP FOR NEWSLETTER":"ПОДПИСАТЬСЯ НА НОВОСТИ"}</span><p>#GITEXAICAC</p><div className="footer-social"><a href="https://www.linkedin.com/company/gitexaikazakhstan/">LinkedIn</a><a href="https://www.instagram.com/gitexaikazakhstan/">Instagram</a><a href="https://www.youtube.com/@GITEXCENTRALASIACAUCASUS">YouTube</a></div></div><div><b>{locale==="en"?"QUICK LINKS":"БЫСТРЫЕ ССЫЛКИ"}</b><a href={`/${locale}/about`}>{locale==="en"?"About":"О мероприятии"}</a><a href="#exhibition">{locale==="en"?"Exhibiting Sectors":"Секторы выставки"}</a><a href={`/${locale}/speakers`}>{locale==="en"?"Speakers":"Спикеры"}</a><a href="#sponsors">{locale==="en"?"Sponsors":"Спонсоры"}</a><a href={`/${locale}/news`}>{locale==="en"?"Newsroom":"Новости"}</a></div><div><b>{locale==="en"?"CONTACT US":"КОНТАКТЫ"}</b><span>{locale==="en"?"Sales Inquiry":"Продажи"}</span><span>{locale==="en"?"Marketing Inquiry":"Маркетинг"}</span><span>{locale==="en"?"Partnership Inquiry":"Партнёрство"}</span><span>{locale==="en"?"Sponsorship Inquiry":"Спонсорство"}</span></div><div><b>7–8 {locale==="en"?"JUNE":"ИЮНЯ"} 2027</b><p>{localized(s,"venue",locale)}<br/>{localized(s,"city",locale)}, {localized(s,"country",locale)}</p></div><small>Copyright 2026. All rights reserved · <a href={`/${locale}/cookie-policy`}>{locale==="en"?"Cookies Policy":"Политика cookie"}</a> · <a href={`/${locale}/terms-and-conditions`}>{locale==="en"?"Terms and Conditions":"Условия использования"}</a> · <a href={`/${locale}/privacy-policy`}>{locale==="en"?"Privacy Policy":"Политика конфиденциальности"}</a></small></footer>
  </main>;
}
