import { notFound } from "next/navigation";
import { getHomepage, json, localized, type Locale } from "@/lib/db";
import { AnimatedCounter } from "@/components/AnimatedCounter";
import { SiteHeader } from "@/components/SiteHeader";

type CTA={label:{en:string;ru:string};href:string;style:string};
export const dynamic="force-dynamic";
export default async function Home({params}:{params:Promise<{locale:string}>}){
  const {locale:raw}=await params; if(raw!=="en"&&raw!=="ru") notFound(); const locale=raw as Locale;
  const d=await getHomepage(locale); const h=d.hero,s=d.settings,x=d.highlights; const ct=json<CTA[]>(h.primary_ctas_json,[]); const gallery=json<string[]>(x.gallery_images_json,[]);
  const section=(key:string)=>d.sections.find(v=>v.section_key===key)!;
  const items=<T,>(key:string)=>json<T[]>(section(key)?.items_json,[]);
  const ecosystem=section("ecosystem"), president=section("president"), government=section("government"), sectors=section("sectors"), tracks=section("tracks"), supernova=section("supernova"), network=section("network");
  return <main>
    <SiteHeader locale={locale} logo={String(s.logo_url)}/>
    <section className="hero"><div className="hero-video"><iframe src="https://www.youtube.com/embed/L06Z9x9Fst4?autoplay=1&mute=1&loop=1&controls=0&modestbranding=1&playsinline=1&rel=0&playlist=L06Z9x9Fst4" title="GITEX AI Kazakhstan" allow="autoplay; encrypted-media"/></div><div className="hero-wash"/><div id="top" className="hero-copy"><img className="lockup" src={String(s.logo_url)} alt="GITEX AI Central Asia & Caucasus Kazakhstan"/><p className="patronage">{localized(h,"patronage_line",locale)}</p><h1>{localized(h,"title",locale)}</h1><h2>{localized(h,"subtitle",locale)}</h2><p className="hero-description">{localized(h,"eyebrow",locale)}</p><div className="actions">{ct.map((c,i)=><a className={c.style} href={c.href} key={i}>{c.label[locale]}</a>)}</div></div><div className="social-rail"><a href="https://www.linkedin.com/company/gitexaikazakhstan/" aria-label="LinkedIn">in</a><a href="https://www.instagram.com/gitexaikazakhstan/" aria-label="Instagram">◎</a><a href="https://www.facebook.com/gitexaikazakhstan" aria-label="Facebook">f</a><a href="https://www.youtube.com/@GITEXCENTRALASIACAUCASUS" aria-label="YouTube">▶</a><a href="https://t.me/gitexaikazakhstan" aria-label="Telegram">➤</a></div></section>
    <section className="gallery"><h2>THE LARGEST AI GATHERING IN THE REGION<br/>THIS IS WHAT IT LOOKED LIKE</h2><div className="gallery-strip">{gallery.slice(0,8).map((url,i)=><img src={url} alt={`GITEX highlight ${i+1}`} key={url}/>)}</div><div className="gallery-actions"><a href="https://www.gitexcac.com/gallery">SEE MORE</a><a href={String(x.factsheet_file_url)}>DOWNLOAD FACTSHEET</a></div></section>
    <section className="highlight-video"><iframe src={String(x.video_embed_url)} title="GITEX AI Kazakhstan highlights" allow="autoplay; encrypted-media"/><h2>WATCH THE HIGHLIGHTS OF<br/>GITEX AI KAZAKHSTAN 2026</h2></section>
    <section className="statement"><p>{localized(x,"title",locale)}</p><h2>{localized(x,"body",locale)}</h2></section>
    <section className="stats-wrap"><h2>THE REGION&apos;S MOST EMPOWERING TECH, STARTUP &amp; DIGITAL<br/>INVESTMENT EVENT CONVERGING POWERFUL ALLIANCES<br/>ACROSS BUSINESS, CAPITAL &amp; POLICY</h2><div className="stats">{d.stats.map((item)=><article key={String(item.id)}><AnimatedCounter value={String(item.value)} suffix={String(item.suffix??"")}/><span>{localized(item,"label",locale)}</span></article>)}</div></section>
    <section className="intro"><div><p className="eyebrow">{localized(ecosystem,"title",locale)}</p><h2>POWERFUL ALLIANCES ACROSS<br/>BUSINESS, CAPITAL &amp; POLICY</h2><p>{localized(ecosystem,"body",locale)}</p><a href="#register">GET INVOLVED</a></div></section>
    <section className="feature-panel president"><div><h2>{localized(president,"title",locale)}</h2><p>{localized(president,"body",locale)}</p><a href="https://www.gitexcac.com/section">READ MORE</a></div><img src={items<{image:string}>("president")[0]?.image} alt="AI Development Council meeting"/></section>
    <section className="testimonials"><h2>{locale==="en"?"TESTIMONIALS":"ОТЗЫВЫ"}</h2><div className="quotes">{d.testimonials.map(t=><blockquote key={String(t.id)}>“{localized(t,"quote",locale)}”<footer><b>{localized(t,"name",locale)}</b><span>{localized(t,"role",locale)} · {localized(t,"company",locale)}</span></footer></blockquote>)}</div></section>
    <section className="government"><video autoPlay muted loop playsInline src={items<{video:string}>("government")[0]?.video}/><div><h2>{localized(government,"title",locale)}</h2><p>{localized(government,"body",locale)}</p><blockquote>“{items<{quote:string}>("government")[0]?.quote}”<b>{items<{name:string}>("government")[0]?.name}</b></blockquote></div></section>
    <section id="programmes" className="programmes"><div className="programme-heading"><h2>{locale==="en"?"FLAGSHIP PROGRAMMES & LIVE EXPERIENCES":"[RU needs review] ФЛАГМАНСКИЕ ПРОГРАММЫ"}</h2><p>Where startups, investors, AI and sustainability collide.</p><div className="programme-tabs"><span>NORTH STAR</span><span>AI EVERYTHING</span><span>CYBER VALLEY</span><span>GREEN IMPACT</span></div></div><div className="programme-stage"><div><h3>CENTRAL ASIA’S LARGEST STARTUP, ACCELERATOR &amp; INVESTOR EVENT</h3><p>{localized(d.programmes[0],"body",locale)}</p><div className="mini-stats"><b>200+<small>STARTUPS</small></b><b>150+<small>INVESTORS</small></b><b>60<small>COUNTRIES</small></b></div><h3>INVESTOR PROGRAMME</h3><p>{localized(d.programmes[1],"body",locale)}</p><details><summary>SUPERNOVA PITCH COMPETITION</summary></details><details><summary>CONNECT WITH 150+ INVESTORS</summary></details><div className="programme-actions"><a href="#investors">JOIN THE INVESTOR PROGRAMME</a><a href="#">BOOK YOUR POD</a></div></div><img src={String(d.programmes[0].image_url)} alt="North Star startup programme"/></div></section>
    <section id="speakers" className="section dark"><p className="eyebrow">{locale==="en"?"GLOBAL MINDS":"[RU needs review] МИРОВЫЕ ЛИДЕРЫ"}</p><h2>{locale==="en"?"Putting the nation’s AI agenda forward":"[RU needs review] Развивая национальную повестку ИИ"}</h2><div className="people">{d.speakers.map(p=><article key={String(p.id)}><div className="portrait" style={{backgroundImage:`url(${String(p.photo_url||"")})`}}/><small>{localized(p,"country",locale)}</small><h3>{localized(p,"name",locale)}</h3><p>{localized(p,"title",locale)}</p><b>{localized(p,"org",locale)}</b></article>)}</div></section>
    <section id="exhibition" className="sectors"><h2>{localized(sectors,"title",locale)}</h2><div>{items<string>("sectors").map((v,i)=><article key={v}><span>{String(i+1).padStart(2,"0")}</span><h3>{v}</h3></article>)}</div></section>
    <section id="themes" className="tracks"><p className="eyebrow">{localized(tracks,"body",locale)}</p><h2>{localized(tracks,"title",locale)}</h2><div>{items<{title:string;body:string;image:string}>("tracks").map(v=><article key={v.title}><img src={v.image} alt=""/><div><h3>{v.title}</h3><p>{v.body}</p></div></article>)}</div><a className="primary" href="#register">PRE-REGISTER TO VISIT</a></section>
    <section id="startup" className="supernova"><div><h2>{localized(supernova,"title",locale)}</h2><p>{localized(supernova,"body",locale)}</p><a href="https://www.gitexcac.com/supernova-pitch-competition">LEARN MORE</a></div><img src={items<{image:string}>("supernova")[0]?.image} alt="Supernova pitch competition"/></section>
    {["sponsor_logos","tech_partners","featured_exhibitors"].map(key=>{const sec=section(key);return <section id={key==="sponsor_logos"?"sponsors":undefined} className={`logo-band ${key}`} key={key}><h2>{localized(sec,"title",locale)}</h2><div>{items<{name:string;image:string}>(key).map(v=><figure key={v.name}><img src={v.image} alt={v.name}/></figure>)}</div></section>})}
    <section className="section news"><p className="eyebrow">{locale==="en"?"NEWSROOM":"НОВОСТИ"}</p><div className="cards">{d.news.map(n=><article className="card" key={String(n.id)}><small>{new Date(String(n.published_at)).toLocaleDateString(locale)}</small><h3>{String(n.title)}</h3><p>{String(n.excerpt)}</p><a href="https://www.gitexcac.com/news">VIEW MORE</a></article>)}</div></section>
    {["ecosystem_partners","media_partners"].map(key=>{const sec=section(key);return <section className={`logo-band ${key}`} key={key}><h2>{localized(sec,"title",locale)}</h2><div>{items<{name:string;image:string}>(key).map(v=><figure key={v.name}><img src={v.image} alt={v.name}/></figure>)}</div></section>})}
    <section className="network"><h2>{localized(network,"title",locale)}</h2><img src={items<{image:string}>("network")[0]?.image} alt="GITEX global technology network"/></section>
    <footer className="site-footer"><div className="footer-brand"><img src={String(s.logo_url)} alt="GITEX AI Kazakhstan"/><span className="newsletter">SIGN UP FOR NEWSLETTER</span><p>#GITEXAICAC</p><div className="footer-social"><a href="https://www.linkedin.com/company/gitexaikazakhstan/">LinkedIn</a><a href="https://www.instagram.com/gitexaikazakhstan/">Instagram</a><a href="https://www.youtube.com/@GITEXCENTRALASIACAUCASUS">YouTube</a></div></div><div><b>QUICK LINKS</b><span>Get Involved</span><a href="#exhibition">Exhibiting Sectors</a><a href="https://www.gitexcac.com/speakers-2026">Speakers</a><a href="#sponsors">Sponsors</a><a href="https://www.gitexcac.com/news">Newsroom</a></div><div><b>CONTACT US</b><span>Sales Inquiry</span><span>Marketing Inquiry</span><span>Partnership Inquiry</span><span>Sponsorship Inquiry</span></div><div><b>7–8 JUNE 2027</b><p>Atakent Exhibition Centre<br/>Almaty, Kazakhstan</p></div><small>Copyright 2026. All rights reserved · <a href="https://www.dwtc.com/en/privacy/">Cookies Policy</a> · <a href="https://www.gitexcac.com/terms-and-conditions">Terms and Conditions</a> · <a href="https://privacy.informa.com/policies/en/?name=in-d-privacy-notice">Privacy Policy</a></small></footer>
  </main>;
}
